# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Python and R for Data Science
author: Emilio Coppa
logo: dist/img/logo.png
copyright: "2024"

exclude_patterns: [ docs, book, old, scripts, README.md, oldbook, dist, plugin, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", venv, venv2, .cache]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache # force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/ercoppa/labds/ # Online location of your book
  # path_to_book: book  # Optional path to your book, relative to the repository root
  branch: docs  # Which branch of the repository should be used when creating links (optional)

html:
  use_issues_button: false
  use_repository_button: false

parse:
  myst_enable_extensions:
    - html_image
    - dollarmath
    - linkify

launch_buttons:
  colab_url: "https://colab.research.google.com"

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
